[build]
rustflags = ["-A", "dead_code", "-A", "mismatched_lifetime_syntaxes"]

[target.aarch64-linux-android]
rustflags = ["-C", "link-arg=-z", "-C", "link-arg=max-page-size=16384", "-A", "dead_code", "-A", "mismatched_lifetime_syntaxes"]

[target.x86_64-linux-android]
rustflags = ["-C", "link-arg=-z", "-C", "link-arg=max-page-size=16384", "-A", "dead_code", "-A", "mismatched_lifetime_syntaxes"]
